# Netlify configuration for Next.js with SSR (no static export)
# Docs: https://docs.netlify.com/integrations/frameworks/next-js/overview/

[build]
  # Use the normal Next.js build (do NOT run `next export`)
  command = "yarn build"
  # The Next.js plugin will handle routing/functions. This directory holds emitted static assets.
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  # Ensure the official Next.js plugin is enabled
  package = "@netlify/plugin-nextjs"

[functions]
  # Recommended for Next.js on Netlify
  node_bundler = "esbuild"
